name: Tests (PHP)

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php
        with:
            php-version: '8.2'

      - name: Run composer update
        run: composer update

      - name: Run tests
        run: composer test
