name: Tests (PHP)

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          php-version: '8.2'
          tools: composer, phpunit'


      - name: Run composer install
        run: composer install

      - name: Run composer update
        run: composer update

      - name: Run tests
        run: ./vendor/bin/phpunit
