name: Tests (PHP)

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run composer update
        run: composer update
        with:
          php-version: 8.2
      - name: Run tests
        run: composer test
        with:
          php-version: 8.2
